### ISSUE TITLE
python 3.8 is deprecated

### ISSUE THREAD

**Issue by MathieuMoalic** [mumax/plus#54]
Hello,

You are recommending to install python 3.8 which is deprecated.
https://endoflife.date/python

Can you consider updating this requirement?

**Comment by ilateur** [comment]
Yes, the [update-versions branch](https://github.com/mumax/plus/tree/update-versions) already deals with this issue :)
You can do a fresh install using that branch, or use the updating instructions of pull request #53 if you want.

**Comment by MathieuMoalic** [comment]
My bad, I missed the PR!
